version: "3"
services:
  api:
    image: sommelier/api:latest
    command: run
    networks:
      - sommelier
    ports:
    - 3000:3000
    env_file:
    - auth.env

  mongo:
    image: mongo:latest
    networks:
      - sommelier
    ports:
      - 27017:27017
    environment:
      - MONGODB_USERNAME=admin
      - MONGODB_PASSWORD=abc123
      - MONGODB_DATABASE=sommelier
      - MONGODB_ROOT_PASSWORD=abc123

  mongo-express:
    image: mongo-express:latest
    networks:
      - sommelier
    depends_on:
      - mongo
    restart: on-failure:5
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=octane_admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=abc123

networks:
  sommelier:
    driver: bridge
