apriori:
  image: apriori:latest
  command: run
  links:
    - postgres
#    - redis
  ports:
    - 3000:3000
  environment:
    DB_HOST: postgres
    DB_PORT: 5432
    DB_NAME: apriori
    DB_USER: apriori
    DB_PASSWORD: "123"
    SCHEMA_VALIDATION: "true"

postgres:
  image: postgres:9.4
  restart: always
  ports:
    - 5432:5432
  environment:
    POSTGRES_USER: apriori
    POSTGRES_PASSWORD: 123
    POSTGRES_DB: apriori

#redis:
#  image: redis:alpine
#  ports:
#    - 6379:6379
#  #environment: