version: "3"
services:
  api:
    image: sommelier/api:latest
    command: run
    depends_on:
      - localstack
      - awscli
    networks:
      - sommelier
    ports:
      - 3000:3000
    environment:
      - AWS_ACCESS_KEY_ID=111
      - AWS_SECRET_ACCESS_KEY=111
      - AWS_REGION=us-east-1
    env_file:
      - auth.env
    restart: on-failure:3

#  apriori:
#    image: sommelier/apriori:latest
#    command: run
#    depends_on:
#      - localstack
#      - awscli
#    networks:
#      - sommelier
#    environment:
#      - AWS_ACCESS_KEY_ID=111
#      - AWS_SECRET_ACCESS_KEY=111
#      - AWS_REGION=us-east-1
#    restart: on-failure:5

#  event:
#    image: sommelier/event:latest
#    command: run
#    depends_on:
#      - localstack
#      - awscli
#    networks:
#      - sommelier
#    environment:
#      - AWS_ACCESS_KEY_ID=111
#      - AWS_SECRET_ACCESS_KEY=111
#      - AWS_REGION=us-east-1
#    restart: on-failure:5

  mongo:
    image: mongo:latest
    networks:
      - sommelier
    restart: on-failure:3
    ports:
      - 27017:27017
    environment:
      - MONGODB_USERNAME=sommelier
      - MONGODB_PASSWORD=abc123
      - MONGODB_DATABASE=sommelier
      - MONGODB_ROOT_PASSWORD=abc123

  mongo-express:
    image: mongo-express:latest
    networks:
      - sommelier
    depends_on:
      - mongo
    restart: on-failure:3
    ports:
      - 8081:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=abc123

  localstack:
    image: localstack/localstack:latest
    networks:
      - sommelier
    ports:
      - "4567-4584:4567-4584"
      - "${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}"
    environment:
      - AWS_REGION=us-east-1
      - SERVICES=sqs
    restart: on-failure:3

  awscli:
    image: mesosphere/aws-cli:latest
    depends_on:
      - localstack
    networks:
      - sommelier
    environment:
      - AWS_ACCESS_KEY_ID=111
      - AWS_SECRET_ACCESS_KEY=111
      - AWS_REGION=us-east-1
    entrypoint: ['/bin/sh', '/usr/local/bin/localstack.sh']
    command: run
    tty: true
    volumes:
      - './localstack.sh:/usr/local/bin/localstack.sh'
    restart: on-failure:3

networks:
  sommelier:
    driver: bridge
