(defproject apriori "0.1.0"
  :dependencies [[org.clojure/clojure "1.8.0"]
                 [org.clojure/tools.cli "0.3.5"]
                 [org.clojure/tools.logging "0.4.0"]
                 [org.clojure/java.jdbc "0.7.3"]
                 [org.clojure/data.json "0.2.6"]
                 [org.clojure/math.combinatorics "0.1.4"]
                 [org.postgresql/postgresql "9.4-1201-jdbc41"]
                 [compojure "1.6.0"]
                 [cheshire "5.8.0"]
                 [clj-sub-command "0.3.0"]
                 [ring "1.6.3"]
                 [ring/ring-json "0.4.0"]
                 [metosin/ring-swagger "0.24.3"]
                 [pg-hstore "3.0.3"]
                 [environ "1.1.0"]
                 [c3p0/c3p0 "0.9.1.2"]
                 [com.h2database/h2 "1.3.168"]]
  ;:plugins [[lein-ring "0.12.1"]]
  :main apriori.cli.core
  :profiles {:uberjar {:aot :all}})